### ISSUE TITLE
Enigma.asm missing constants

### ISSUE THREAD

**Issue by ComputerNerd** [flamewing/mdcomp#12]
I cannot assemble Enigma.asm because it uses the following constants:
* high_priority
* palette_line_2
* palette_line_1
* flip_y
* flip_x

Definitions are not provided for these.

**Comment by flamewing** [comment]
That is because I extracted it from S2 disassembly; I still have to go through and optimize it like the LZSS-based algorithms.

But in any case, I should add the constants.
