### ISSUE TITLE
Missing #include in lzss.h

### ISSUE THREAD

**Issue by Clownacy** [flamewing/mdcomp#4]
Now that MSVC actually supports modern C++ (supposedly), I tried to see if this would compile in [the shell extension](https://github.com/MainMemory/FW-KENSC-ShellExt) without modification, but I got an error in lzss.h about std:min and std:max not being defined. Apparently min and max are defined in \<algorithm\>, which isn't included.

**Comment by flamewing** [comment]
I think GCC and clang may include it in one of the other headers, and pick them up transitively. Anyway, fixed in master.
