### ISSUE TITLE
Some problems building with MSVC

### ISSUE THREAD

**Issue by Clownacy** [flamewing/mdcomp#6]
In `basic_decoder.hh`, I had to add an `#undef max`, so the line `Src.ignore(std::numeric_limits<std::streamsize>::max());` would compile correctly.

I also had to remove the `#elif defined(_MSC_VER)` code in `slog2` in `enigma.cc` because `_BitScanReverse` and the uninitialised variable apparently aren't constexpr-friendly.

**Comment by marzojr** [comment]
Out of curiosity, what version of the MSVC compiler are you using? I just discovered that up to 19.10, they are not fully c++14 compliant, and I will have to add a workaround in some code I am optimizing.

**Comment by flamewing** [comment]
Out of curiosity, what version of the MSVC compiler are you using? I just discovered that up to 19.10, they are not fully c++14 compliant, and I will have to add a workaround in some code I am optimizing.

**Comment by Clownacy** [comment]
19.14.26433. I just updated to Visual Studio 15.7.5.

**Comment by flamewing** [comment]
Then you are safe. Anyway, it if fixed locally; will close it when I push the changes.

**Comment by flamewing** [comment]
Another possibility for max: can you edit your project to globally define NOMINMAX (in VS2015, it was Properties -> C/C++ -> Preprocessor -> append to Preprocessor Definitions).

Doing this way has the advantage that it prevents the issue from happening in the future.

**Comment by Clownacy** [comment]
Oh, didn't know about that. Yeah, that works.
